# Tarefa 03

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os Tutores
- Divirta-se :)

In [319]:
import pandas as pd
import requests

####  1) Lendo de APIs
Vimos em aula como carregar dados públicos do governo através de um API (*Application Programming Interface*). No exemplo de aula, baixamos os dados de pedidos de verificação de limites (PVL) realizados por estados, e selecionamos apenas aqueles referentes ao estado de São Paulo.

1. Repita os mesmos passos feitos em aula, mas selecione os PVLs realizados por municípios no estado do Rio de Janeiro.
2. Quais são os três *status* das solicitações mais frequentes na base? Quais são suas frequências?
3. Construa uma nova variável que contenha o ano do **status**. Observe que ```data_status``` vem como tipo *object* no **DataFrame**. Dica: você pode usar o método ```.str``` para transformar o tipo da variável em string, em seguida um método como [**slice()**](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.slice.html) ou [**split()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html).
4. Indique a frequência de cada ano do campo construído no item (3).

In [321]:
# 1) seu codigo aqui
aprovacoes = pd.read_csv('https://dadosabertos.bndes.gov.br/dataset/bce5a865-e766-4a7a-b537-9499c81275b6/resource/08f7a11c-48e0-4d3e-9a75-d95641657ebf/download/aprovacoes-por-uf-aprovacoes.csv', sep=';')
aprovacoes.head(5)

,ano,mes,acre,amapa,amazonas,para,rondonia,roraima,tocantins,alagoas,...,minas_gerais,rio_de_janeiro,sao_paulo,parana,rio_grande_do_sul,santa_catarina,distrito_federal,goias,mato_grosso,mato_grosso_do_sul
0,1995,1,"0,41869679","0,0","2,23413839","1,84649181","1,04473767","0,0","0,43530234","3,90345966",...,"24,21161259","121,27492154","160,95511135","44,50362458","37,59527024","35,30349192","1,9437482","8,34773228","16,27915326","10,26813495"
1,1995,2,"0,04578434","0,0","2,74517813","42,48085156","0,36960426","0,0","0,64214309","2,29334262",...,"26,77981918","43,42129588","150,04287144","30,00488924","127,62421063","25,61771037","6,73717989","4,2283233","17,33613937","2,98495465"
2,1995,3,"0,58793111","0,0","4,25038413","7,07201709","1,88492287","0,07966938","2,90366427","22,91684798",...,"40,38929874","79,26081391","195,14362719","67,2498400399999","79,49332923","61,3169039300001","4,32211726","17,28640648","40,58887985","15,20808378"
3,1995,4,"0,89306092","0,0","3,3856354","2,73554948","1,96426615","0,0","0,45580241","3,14556117",...,"26,27111669","27,59569635","125,44047338","82,1440808699999","32,5009858","34,56431305","12,23890039","55,16413558","27,22989044","9,6569057"
4,1995,5,"0,0","0,0","7,20134534","2,85948656","1,7582694","0,27605299","1,27020107","1,558083",...,"35,18044643","63,30204158","222,39367098","81,67998936","49,01467171","39,63988675","4,58714604","33,5075155","14,40645992","6,61725569"

In [323]:
# 2) Seu código aqui
aprovacoes['ano'].unique()

array([1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [325]:
aprovacoes['ano'].nunique()

30

In [327]:
aprovacoes['mes'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [329]:
aprovacoes['mes'].nunique()

12

In [331]:
aprovacoes.columns.unique()

Index(['ano', 'mes', 'acre', 'amapa', 'amazonas', 'para', 'rondonia',
       'roraima', 'tocantins', 'alagoas', 'bahia', 'ceara', 'maranhao',
       'paraiba', 'pernambuco', 'piaui', 'rio_grande_do_norte', 'sergipe',
       'espirito_santo', 'minas_gerais', 'rio_de_janeiro', 'sao_paulo',
       'parana', 'rio_grande_do_sul', 'santa_catarina', 'distrito_federal',
       'goias', 'mato_grosso', 'mato_grosso_do_sul'],
      dtype='object')

In [333]:
aprovacoes.loc[:,'rio_de_janeiro':].columns.unique()

Index(['rio_de_janeiro', 'sao_paulo', 'parana', 'rio_grande_do_sul',
       'santa_catarina', 'distrito_federal', 'goias', 'mato_grosso',
       'mato_grosso_do_sul'],
      dtype='object')

In [335]:
aprovacoes.loc[:,'rio_de_janeiro':].columns.nunique()

9

In [337]:
# 3) Seu código aqui
data = {'data_status': ['1995', '1996', '2000']}
df = pd.DataFrame(data)

# Convertendo a coluna 'data_status' para string
df['data_status'] = df['data_status'].astype(str)

# Extraindo o ano usando o método str e o método slice
df['ano_status'] = df['data_status'].str[:4]

print(df)

  data_status ano_status
0        1995       1995
1        1996       1996
2        2000       2000

In [339]:
# 4) seu codigo aqui

data = {'data_status': ['1995', '1996', '2000']}
df = pd.DataFrame(data)

# Convertendo a coluna 'data_status' para string
df['data_status'] = df['data_status'].astype(str)

# Extraindo o ano usando o método str e o método slice
df['ano_status'] = df['data_status'].str[:4]

# Calculando a frequência de cada ano
frequencia_ano = df['ano_status'].value_counts()

print(frequencia_ano)

ano_status
1995    1
1996    1
2000    1
Name: count, dtype: int64

####  2) Melhorando a interação com o API
Observe dois URLs de consultas diferentes, por exemplo o URL utilizado em aula, e o URL feito no exercício anterior. Compare-os e observe as diferenças.

1. Faça uma função em Python que recebe como argumento o UF da consulta e o tipo de interessado (```'Estado'```ou ```Município```), e que devolve os dados da consulta no formato *DataFrame*.
2. Quantas solicitações para o Estado podem ser consultadas para Minas Gerais com *status* em 'Arquivado por decurso de prazo' estão registradas?
3. Qual é o município da Bahia com mais solicitações deferidas?
4. Salve um arquivo .csv com os dados de solicitações da Bahia, com interessado = 'Estado'

In [342]:
def consulta_dados(data: List[Dict[str, str]], uf: str, tipo_interessado: str) -> pd.DataFrame:
    """
    Filters the dataset based on the specified state and interested type.

    Args:
    data (List[Dict[str, str]]): The dataset to filter, where each entry is a dictionary.
    uf (str): The state to filter by (e.g., "rio_de_janeiro").
    tipo_interessado (str): The type of interest to filter by (e.g., "Município").

    Returns:
    pd.DataFrame: A DataFrame containing the filtered data.
    """
    # Filter the dataset based on the specified state and type of interest
    dados_filtrados = [entry for entry in data if entry["rio_de_janeiro"] == uf and entry["Tipo"] == tipo_interessado]

    # Convert the list of dictionaries to a DataFrame
    df = pd.DataFrame(dados_filtrados)

    return df

In [344]:
aprovacoes['minas_gerais'].unique()

array(['24,21161259', '26,77981918', '40,38929874', '26,27111669',
       '35,18044643', '73,6919255', '29,05583257', '49,2032939',
       '51,45626786', '161,29618259', '52,12925163', '307,77272089',
       '18,93690689', '199,30633334', '51,74237988', '32,80996697',
       '148,63046963', '52,81080117', '50,72030378', '26,60236367',
       '26,93056265', '32,22854267', '40,14625678', '100,12232205',
       '114,07562614', '30,11660015', '43,63977722', '551,41325911',
       '51,78468083', '660,343296870001', '39,28684518', '68,19858694',
       '120,1203521', '70,1443889100001', '51,81380587', '72,27019833',
       '49,00599988', '170,61928397', '92,77648243', '201,0524778',
       '386,26049197', '84,02028412', '115,65757373', '68,33191948',
       '146,37483779', '92,63998063', '48,02207766', '361,17452491',
       '27,0745781', '142,4380258', '22,64473716', '541,34564371',
       '128,27291816', '218,60164766', '206,85420884', '100,66129505',
       '131,53689491', '38,97958678', '361,84870713', '156,83172388',
       '33,72575862', '398,38455081', '177,55502147', '76,64048787',
       '107,55720989', '144,5222962', '78,26837526', '102,71773231',
       '333,83824014', '108,91785384', '797,29888143', '167,89858093',
       '112,60590826', '87,99044795', '39,51552824', '38,11048646',
       '140,94118823', '68,83743341', '70,1247060000001', '102,3262857',
       '81,8014481299999', '101,66552955', '133,80332551', '428,13086997',
       '516,53008999', '97,9776939', '205,64111779', '222,43651063',
       '116,24953852', '113,9234524', '79,5192181100001', '266,47833477',
       '204,07006176', '243,06562274', '168,23219809', '580,43599706',
       '119,05616586', '114,21723074', '92,2616111900001', '97,72312352',
       '252,94459512', '666,75258247', '327,53545964', '363,94841141',
       '152,41471023', '878,37426901', '169,41636993', '770,058295130001',
       '104,40432677', '109,93222714', '241,65079076', '467,69635561',
       '126,41408936', '476,29241843', '71,77795238', '117,47806583',
       '149,49776517', '221,25598914', '356,98647253', '297,2542266',
       '137,63029462', '126,87204007', '204,75573082', '185,37817515',
       '431,53610465', '493,51528433', '321,30086255', '238,38795922',
       '175,70475397', '535,87227495', '293,54307339', '586,42750194',
       '137,94870719', '120,03636328', '147,02076736', '285,099505',
       '300,19094748', '1243,28772381', '424,37061887',
       '955,457114670001', '297,60749522', '457,59729414', '311,27125179',
       '631,61970027', '177,85228139', '191,55516384', '1269,33116636',
       '303,16544789', '417,03255049', '525,79355381', '1047,18238183',
       '858,494156100001', '962,265910500001', '394,57258365',
       '958,426737500001', '3019,13731013', '256,06217143',
       '388,96128619', '492,663819', '1707,03411227', '531,88687042',
       '1871,52133617', '543,52634085', '950,48407751', '2610,80262093',
       '5726,43715212', '1316,09524034', '461,9445072',
       '600,825102450001', '442,22527911', '346,68777233',
       '639,270075720001', '348,78098705', '2499,69462665',
       '648,74630671', '1307,26992218', '942,537589940001',
       '732,550132210001', '833,311895389999', '2715,32215168',
       '712,530200630002', '1102,38672391', '1152,74713782',
       '1496,65399263', '1340,48211142001', '2669,89331689',
       '1156,07823647', '1539,78748018', '790,218306340001',
       '635,559841480002', '1928,16400609', '1208,28717125',
       '712,217177200001', '2092,57924517', '846,658729740001',
       '476,18188985', '1310,22070935', '943,602188090001',
       '932,72978702', '1419,54121273001', '3494,94550452002',
       '939,418965530004', '1789,00706006001', '706,523978160003',
       '659,312384510002', '857,446629020001', '1425,84300455',
       '914,305623460006', '917,21321779', '1889,58018817',
       '1705,69763605', '2683,15753678002', '724,571571719997',
       '2648,9211706', '1188,01260216', '2853,49531138',
       '557,024108680001', '1429,77449372', '1141,17404474',
       '1614,19812226999', '1009,6560267', '1362,11938833',
       '850,907486829998', '3060,53380424003', '2083,34600136998',
       '1917,65083204', '1651,0155956', '2831,89392725001',
       '685,491851130001', '716,817209569998', '746,946570330002',
       '1477,68124405', '1059,34154618', '2165,62117548',
       '1325,86666370001', '2157,37169272001', '1184,54250393',
       '1533,32829001', '1040,87180438', '2400,38163946999',
       '320,468576120001', '256,514258710001', '477,614453239999',
       '608,437015949996', '489,6083232', '625,783369490001',
       '779,385354640002', '722,00609736', '1772,33031266',
       '1475,99406793', '855,907652639997', '2399,07897789',
       '307,278022479999', '3078,95382087001', '470,000604090001',
       '417,161995279999', '759,518589330002', '1964,91083549001',
       '269,96472491', '355,49238351', '337,916202690001', '321,32824391',
       '1348,32210502', '1193,33513844', '265,88833787', '302,93074421',
       '434,14898821', '372,549361819999', '1011,34417948',
       '453,472431580001', '392,175704370001', '448,421881569999',
       '379,95844651', '680,821293280001', '430,38199311',
       '827,848073760002', '234,84592156', '301,309956580001',
       '381,87494069', '589,485512490001', '357,27749263',
       '731,594199059999', '447,34718697', '427,70128944', '439,02548214',
       '1600,9201379', '891,736346840001', '1471,38397385',
       '323,55442618', '251,62872514', '1405,00701638', '427,48040855',
       '521,55823998', '767,626809980001', '208,23007942', '335,47360695',
       '363,575120640001', '673,36363833', '4138,68866111',
       '623,389796550001', '301,21785561', '192,92463091', '335,25430393',
       '396,532480150001', '587,15312896', '409,92545864', '434,15533253',
       '683,67365639', '604,110490099999', '720,80998624', '423,23875485',
       '431,51980943', '402,77009899', '225,09693202', '420,08576341',
       '1854,38566383', '237,08907845', '390,15242931', '618,18485198',
       '761,70528967', '678,50641863', '397,10795353', '382,01369472',
       '421,57056216', '347,5437239', '427,11677729', '403,50999476',
       '347,64473005', '558,07290181', '1376,18524191',
       '858,535168630001', '1378,60610507', '984,24529272',
       '1000,45232485', '804,76805208', '2408,34974375', '400,51257694',
       '794,77824024', '521,34083868', '548,73512533', '508,3502755',
       '871,818455239999', '1377,0547156', '2089,74062709',
       '963,146037720001', '1264,01132212', '3151,97223186',
       '1819,3574625', '1281,72429398', '865,31345408', '787,2379321',
       '1294,64413281', '911,664237480001', '847,69297797',
       '1879,58427483', '2622,24125849', '1180,23309525'], dtype=object)

In [346]:
# 3) Seu código aqui
aprovacoes['bahia'].unique()

array(['18,00609295', '41,57228056', '176,63088896', '27,50283739',
       '94,7475339399999', '35,54758735', '25,3748502', '24,59331823',
       '94,76164611', '80,1433107000001', '67,90628294', '50,67683796',
       '49,97655478', '12,67367918', '16,28233391', '18,73150087',
       '157,99357883', '26,67263709', '33,50076334', '24,32217229',
       '79,2123813', '110,87188671', '37,41696201', '14,67405694',
       '41,85513967', '30,83854492', '64,72901597', '32,78450964',
       '56,70988968', '85,73367129', '500,40921191', '22,24407404',
       '29,19486885', '54,75100438', '131,16934108', '85,63749377',
       '37,37950796', '58,70150926', '88,1261996', '61,57315795',
       '26,09951947', '57,58459141', '73,1001882', '165,79522865',
       '117,61435645', '36,67574461', '48,84584322', '77,44447457',
       '29,65283286', '122,87037262', '15,79742801', '21,13077651',
       '185,75137737', '27,94548981', '40,33366317', '33,49225832',
       '28,61355121', '161,74881247', '942,133468100001', '70,03487408',
       '21,16894663', '15,56755652', '32,49768877', '34,48316727',
       '46,76503622', '51,18806337', '28,11938214', '55,41136705',
       '38,93930152', '591,61367838', '281,42058871', '876,110046810002',
       '68,5354238', '19,64756458', '22,22847641', '39,80898584',
       '34,16856937', '257,05329774', '236,76587471', '372,63578469',
       '75,87527237', '37,97522443', '30,90949509', '201,62386286',
       '342,11898805', '50,02863847', '59,46908207', '158,14322519',
       '82,67677195', '33,84888888', '38,67308225', '261,3264096',
       '191,23021852', '62,21916318', '22,08745168', '435,31047361',
       '42,55681162', '36,58675909', '43,24235403', '39,81652195',
       '42,02769476', '404,14862702', '18,18195758', '48,31016103',
       '49,56570129', '265,94679914', '148,01489455', '1715,70940341',
       '39,50576725', '42,28883732', '142,56061929', '31,44636731',
       '43,03183721', '103,04955471', '26,60966617', '23,30726942',
       '38,45574569', '44,86124013', '567,1864144', '72,1486216',
       '64,02057464', '50,21774398', '241,01017856', '432,07164773',
       '395,58581293', '290,38193881', '40,73309033', '125,23502985',
       '50,00259962', '2643,42118982', '834,27619739', '168,51880378',
       '80,44167006', '30,62160184', '34,68662115', '482,90858376',
       '33,36477238', '230,86364438', '36,19592067', '148,52634833',
       '121,64216529', '98,30493077', '81,340021', '1784,76105415',
       '58,34253008', '48,74339309', '52,87023012', '655,219024009998',
       '69,6807082300001', '82,29208813', '229,81351336', '84,90841132',
       '342,92030605', '71,14793538', '248,10075361', '4182,97932495',
       '63,73207587', '134,96629498', '291,70967174', '81,49472653',
       '89,95495714', '171,07497141', '162,59504775', '97,4181882',
       '120,80612338', '114,65422223', '157,61580506', '209,55791136',
       '62,0857891', '147,99767142', '182,27783198', '251,12157638',
       '160,33149385', '1426,78940826', '98,94921138', '113,56431099',
       '580,15956026', '320,08477994', '682,609504950003',
       '496,799462040001', '282,81818084', '190,07405303', '454,26075825',
       '157,24934092', '399,45563478', '943,461822830001', '233,97411315',
       '700,683182369999', '555,75883704', '217,17898497', '221,16115798',
       '953,785646190001', '165,37210518', '223,55870766', '215,91050354',
       '1391,26569522', '203,25017521', '236,79955321', '202,5172029',
       '1213,70724342', '560,88233445', '288,15946185',
       '408,815056079998', '205,83355891', '250,49946896', '305,49886724',
       '220,16272059', '471,827025199999', '688,05483438',
       '2076,07068182', '273,762311119999', '697,034795060001',
       '861,229394270002', '292,859183750001', '3381,52672809999',
       '1433,50134126', '239,90628984', '416,081058059999',
       '2392,71049829', '289,663277920001', '311,69035527',
       '826,41812357', '297,913186390001', '286,148424630001',
       '429,18803153', '193,85756394', '869,43553481', '2190,16256151',
       '255,47135062', '239,95631352', '267,82828287', '243,64849724',
       '247,39520981', '1131,35748578', '306,11479003',
       '286,567908120001', '579,61359283', '370,868938590001',
       '529,582665540001', '1464,72415781', '84,7598070699999',
       '575,826751499999', '185,71005384', '357,07781063', '218,63028615',
       '610,988279340001', '175,59449061', '315,60877911',
       '708,519137660001', '191,72936365', '1769,73466389',
       '378,782001719999', '91,4645933499999', '87,2457380299999',
       '100,33902976', '198,08671691', '391,72691967', '106,48508304',
       '65,5823387200001', '365,431544', '97,8279891799999',
       '92,04814582', '140,55445573', '120,3442247', '913,803841639999',
       '62,47964905', '272,70723932', '102,39915738', '706,802359590001',
       '1329,36602589', '389,54736285', '723,685582860001', '84,16572279',
       '90,30198074', '160,09629326', '1932,63984051', '646,713822300001',
       '79,76692949', '107,78259971', '84,2898652000001',
       '81,7979150000001', '208,13743219', '98,9046052900001',
       '110,97110464', '93,05738808', '388,59529694', '86,00945965',
       '1891,2767948', '47,33468857', '46,34100039', '235,42564091',
       '72,4876653300001', '52,40181145', '63,26371737', '62,93521445',
       '475,35900111', '1335,91552788', '108,17051895', '469,28395496',
       '217,73279398', '55,30420147', '37,86449397', '1344,40778859',
       '170,14563717', '70,23671937', '80,34552989', '114,23387792',
       '1681,28547908', '112,09922104', '1026,38167953', '109,00258491',
       '55,34434137', '105,80419342', '61,01918404', '73,0676326',
       '63,3729699', '99,18844721', '86,93007554', '71,61140911',
       '135,12993828', '3182,6715931', '99,82035942', '747,52238079',
       '63,06811653', '49,91842384', '72,3305613099999', '101,09706622',
       '65,72326612', '71,35701218', '548,30532962', '445,081612',
       '637,72653382', '163,27534926', '173,43989179', '219,45434291',
       '2499,67448537', '86,27059513', '140,39241993', '78,9359358',
       '70,35973071', '307,69277546', '290,55750602', '326,94162716',
       '1055,10148377', '178,58916191', '1266,868117', '381,7219848',
       '4157,2896736', '216,28071365', '201,72354479', '376,85237624',
       '255,75799187', '1639,8784688', '111,12028397', '337,29567244',
       '370,37385424', '263,40862859'], dtype=object)

In [374]:
# Carregar os dados CSV
aprovacoes = pd.read_csv(
    'https://dadosabertos.bndes.gov.br/dataset/bce5a865-e766-4a7a-b537-9499c81275b6/resource/08f7a11c-48e0-4d3e-9a75-d95641657ebf/download/aprovacoes-por-uf-aprovacoes.csv',
    sep=';')

# Verificar os valores únicos na coluna 'bahia'
print(aprovacoes['bahia'].unique())

# Filtrar dados da Bahia com interessado = 'Estado'
df_bahia_estado = aprovacoes[(aprovacoes['uf'] == 'Bahia') & (aprovacoes['Interessado'] == 'Estado')]

# Exibir o DataFrame filtrado
print(df_bahia_estado)

# Salvar DataFrame filtrado em um novo arquivo CSV
df_bahia_estado.to_csv('solicitacoes_bahia_estado.csv', index=False)

print("Arquivo CSV salvo com sucesso!")

['18,00609295' '41,57228056' '176,63088896' '27,50283739'
 '94,7475339399999' '35,54758735' '25,3748502' '24,59331823' '94,76164611'
 '80,1433107000001' '67,90628294' '50,67683796' '49,97655478'
 '12,67367918' '16,28233391' '18,73150087' '157,99357883' '26,67263709'
 '33,50076334' '24,32217229' '79,2123813' '110,87188671' '37,41696201'
 '14,67405694' '41,85513967' '30,83854492' '64,72901597' '32,78450964'
 '56,70988968' '85,73367129' '500,40921191' '22,24407404' '29,19486885'
 '54,75100438' '131,16934108' '85,63749377' '37,37950796' '58,70150926'
 '88,1261996' '61,57315795' '26,09951947' '57,58459141' '73,1001882'
 '165,79522865' '117,61435645' '36,67574461' '48,84584322' '77,44447457'
 '29,65283286' '122,87037262' '15,79742801' '21,13077651' '185,75137737'
 '27,94548981' '40,33366317' '33,49225832' '28,61355121' '161,74881247'
 '942,133468100001' '70,03487408' '21,16894663' '15,56755652'
 '32,49768877' '34,48316727' '46,76503622' '51,18806337' '28,11938214'
 '55,41136705' '38,93930152' '591,61367838' '281,42058871'
 '876,110046810002' '68,5354238' '19,64756458' '22,22847641' '39,80898584'
 '34,16856937' '257,05329774' '236,76587471' '372,63578469' '75,87527237'
 '37,97522443' '30,90949509' '201,62386286' '342,11898805' '50,02863847'
 '59,46908207' '158,14322519' '82,67677195' '33,84888888' '38,67308225'
 '261,3264096' '191,23021852' '62,21916318' '22,08745168' '435,31047361'
 '42,55681162' '36,58675909' '43,24235403' '39,81652195' '42,02769476'
 '404,14862702' '18,18195758' '48,31016103' '49,56570129' '265,94679914'
 '148,01489455' '1715,70940341' '39,50576725' '42,28883732' '142,56061929'
 '31,44636731' '43,03183721' '103,04955471' '26,60966617' '23,30726942'
 '38,45574569' '44,86124013' '567,1864144' '72,1486216' '64,02057464'
 '50,21774398' '241,01017856' '432,07164773' '395,58581293' '290,38193881'
 '40,73309033' '125,23502985' '50,00259962' '2643,42118982' '834,27619739'
 '168,51880378' '80,44167006' '30,62160184' '34,68662115' '482,90858376'
 '33,36477238' '230,86364438' '36,19592067' '148,52634833' '121,64216529'
 '98,30493077' '81,340021' '1784,76105415' '58,34253008' '48,74339309'
 '52,87023012' '655,219024009998' '69,6807082300001' '82,29208813'
 '229,81351336' '84,90841132' '342,92030605' '71,14793538' '248,10075361'
 '4182,97932495' '63,73207587' '134,96629498' '291,70967174' '81,49472653'
 '89,95495714' '171,07497141' '162,59504775' '97,4181882' '120,80612338'
 '114,65422223' '157,61580506' '209,55791136' '62,0857891' '147,99767142'
 '182,27783198' '251,12157638' '160,33149385' '1426,78940826'
 '98,94921138' '113,56431099' '580,15956026' '320,08477994'
 '682,609504950003' '496,799462040001' '282,81818084' '190,07405303'
 '454,26075825' '157,24934092' '399,45563478' '943,461822830001'
 '233,97411315' '700,683182369999' '555,75883704' '217,17898497'
 '221,16115798' '953,785646190001' '165,37210518' '223,55870766'
 '215,91050354' '1391,26569522' '203,25017521' '236,79955321'
 '202,5172029' '1213,70724342' '560,88233445' '288,15946185'
 '408,815056079998' '205,83355891' '250,49946896' '305,49886724'
 '220,16272059' '471,827025199999' '688,05483438' '2076,07068182'
 '273,762311119999' '697,034795060001' '861,229394270002'
 '292,859183750001' '3381,52672809999' '1433,50134126' '239,90628984'
 '416,081058059999' '2392,71049829' '289,663277920001' '311,69035527'
 '826,41812357' '297,913186390001' '286,148424630001' '429,18803153'
 '193,85756394' '869,43553481' '2190,16256151' '255,47135062'
 '239,95631352' '267,82828287' '243,64849724' '247,39520981'
 '1131,35748578' '306,11479003' '286,567908120001' '579,61359283'
 '370,868938590001' '529,582665540001' '1464,72415781' '84,7598070699999'
 '575,826751499999' '185,71005384' '357,07781063' '218,63028615'
 '610,988279340001' '175,59449061' '315,60877911' '708,519137660001'
 '191,72936365' '1769,73466389' '378,782001719999' '91,4645933499999'
 '87,2457380299999' '100,33902976' '198,08671691' '391,72691967'
 '106,48508304' '65,5823387200001' '365,431544' '97,8279891799999'
 '92,04814582' '140,55445573' '120,3442247' '913,803841639999'
 '62,47964905' '272,70723932' '102,39915738' '706,802359590001'
 '1329,36602589' '389,54736285' '723,685582860001' '84,16572279'
 '90,30198074' '160,09629326' '1932,63984051' '646,713822300001'
 '79,76692949' '107,78259971' '84,2898652000001' '81,7979150000001'
 '208,13743219' '98,9046052900001' '110,97110464' '93,05738808'
 '388,59529694' '86,00945965' '1891,2767948' '47,33468857' '46,34100039'
 '235,42564091' '72,4876653300001' '52,40181145' '63,26371737'
 '62,93521445' '475,35900111' '1335,91552788' '108,17051895'
 '469,28395496' '217,73279398' '55,30420147' '37,86449397' '1344,40778859'
 '170,14563717' '70,23671937' '80,34552989' '114,23387792' '1681,28547908'
 '112,09922104' '1026,38167953' '109,00258491' '55,34434137'
 '105,80419342' '61,01918404' '73,0676326' '63,3729699' '99,18844721'
 '86,93007554' '71,61140911' '135,12993828' '3182,6715931' '99,82035942'
 '747,52238079' '63,06811653' '49,91842384' '72,3305613099999'
 '101,09706622' '65,72326612' '71,35701218' '548,30532962' '445,081612'
 '637,72653382' '163,27534926' '173,43989179' '219,45434291'
 '2499,67448537' '86,27059513' '140,39241993' '78,9359358' '70,35973071'
 '307,69277546' '290,55750602' '326,94162716' '1055,10148377'
 '178,58916191' '1266,868117' '381,7219848' '4157,2896736' '216,28071365'
 '201,72354479' '376,85237624' '255,75799187' '1639,8784688'
 '111,12028397' '337,29567244' '370,37385424' '263,40862859']

KeyError: 'uf'